# Generated by Django 5.1.7 on 2025-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
