# Generated by Django 5.1.7 on 2025-04-08 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must be between 10 and 15 digits.', regex='^\\d{10,15}$')]),
        ),
    ]
